[Server]
# Configuration params for the HTTP server hosting the site
host=0.0.0.0
port=3475

# SMTP Mail parameters
smtp_host=smtp.gmail.com
smtp_user=
smtp_pass=

# Recaptcha parameters
recaptcha_v2_key=
recaptcha_project_id=
recaptcha_action=
# location of service account credentials file for re-captcha api authentication
recaptcha_credentials_file=

[Blog]
# Configuration params for the Blog portion of the portfolio site
blog_path=/var/lib/portfolio/posts
